[package]
name = "msg-store-plugin-leveldb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { version = "1.3.3" }
db-key = { version = "0.0.5" }
leveldb = { version = "0.8.6" }
msg-store = { path = "../msg-store" }
serde = { version = "1.0", features = ["derive"] }